spring.application.name=artifactstore
server.port=5000

server.ssl.key-store=/var/lib/tailscale/certs/keystore.p12
server.ssl.key-store-password=marley
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=registry

spring.datasource.url=jdbc:postgresql://tonga.pt:5432/artifactstore
spring.datasource.username=artifactstore
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.sql.init.mode=always

logging.level.org.springframework.jdbc=DEBUG

